config/routes.rb
OrderSystemJameszachary::Application.routes.draw do
  resources :taxes

  resources :order_lines

  resources :tickets

  resources :menus

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :dessert, :drink, :entree, :id, :main_course, :price, :side_dish
  has_many :order_lines
  has_many :tickets, through: :order_lines
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :entree %><br />
    <%= f.text_field :entree %>
  </div>
  <div class="field">
    <%= f.label :main_course %><br />
    <%= f.text_field :main_course %>
  </div>
  <div class="field">
    <%= f.label :side_dish %><br />
    <%= f.text_field :side_dish %>
  </div>
  <div class="field">
    <%= f.label :dessert %><br />
    <%= f.text_field :dessert %>
  </div>
  <div class="field">
    <%= f.label :drink %><br />
    <%= f.text_field :drink %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Edit Menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Menu Items</h1>

<table>
  <tr>

    <th>Entree</th>
    <th>Main Course</th>
    <th>Side Dish</th>
    <th>Dessert</th>
    <th>Drink</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>

    <td><%= menu.entree %></td>
    <td><%= menu.main_course %></td>
    <td><%= menu.side_dish %></td>
    <td><%= menu.dessert %></td>
    <td><%= menu.drink %></td>
    <td><%= menu.price %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <b>Entree:</b>
  <%= @menu.entree %>
</p>

<p>
  <b>Main course:</b>
  <%= @menu.main_course %>
</p>

<p>
  <b>Side dish:</b>
  <%= @menu.side_dish %>
</p>

<p>
  <b>Dessert:</b>
  <%= @menu.dessert %>
</p>

<p>
  <b>Drink:</b>
  <%= @menu.drink %>
</p>

<p>
  <b>Price:</b>
  <%= @menu.price %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>