config/routes.rb
OrderSystemJameszachary::Application.routes.draw do
  resources :taxes

  resources :order_lines

  resources :tickets

  resources :menus

end

app/models/tax.rb
class Tax < ActiveRecord::Base
  attr_accessible :tax_rate
end

app/controllers/taxes_controller.rb
class TaxesController < ApplicationController
  # GET /taxes
  # GET /taxes.json
  def index
    @taxes = Tax.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taxes }
    end
  end

  # GET /taxes/1
  # GET /taxes/1.json
  def show
    @taxis = Tax.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxis }
    end
  end

  # GET /taxes/new
  # GET /taxes/new.json
  def new
    @taxis = Tax.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxis }
    end
  end

  # GET /taxes/1/edit
  def edit
    @taxis = Tax.find(params[:id])
  end

  # POST /taxes
  # POST /taxes.json
  def create
    @taxis = Tax.new(params[:taxis])

    respond_to do |format|
      if @taxis.save
        format.html { redirect_to @taxis, notice: 'Tax was successfully created.' }
        format.json { render json: @taxis, status: :created, location: @taxis }
      else
        format.html { render action: "new" }
        format.json { render json: @taxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taxes/1
  # PUT /taxes/1.json
  def update
    @taxis = Tax.find(params[:id])

    respond_to do |format|
      if @taxis.update_attributes(params[:taxis])
        format.html { redirect_to @taxis, notice: 'Tax was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxes/1
  # DELETE /taxes/1.json
  def destroy
    @taxis = Tax.find(params[:id])
    @taxis.destroy

    respond_to do |format|
      format.html { redirect_to taxes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/taxes_helper.rb
module TaxesHelper
end

app/views/taxes/_form.html.erb
<%= form_for(@taxis) do |f| %>
  <% if @taxis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taxis.errors.count, "error") %> prohibited this taxis from being saved:</h2>

      <ul>
      <% @taxis.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tax_rate %><br />
    <%= f.text_field :tax_rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taxes/edit.html.erb
<h1>Editing taxis</h1>

<%= render 'form' %>

<%= link_to 'Show', @taxis %> |
<%= link_to 'Back', taxes_path %>

app/views/taxes/index.html.erb
<h1>Listing taxes</h1>

<table>
  <tr>
    <th>Tax rate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @taxes.each do |taxis| %>
  <tr>
    <td><%= taxis.tax_rate %></td>
    <td><%= link_to 'Show', taxis %></td>
    <td><%= link_to 'Edit', edit_taxis_path(taxis) %></td>
    <td><%= link_to 'Destroy', taxis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tax', new_taxis_path %>

app/views/taxes/new.html.erb
<h1>New taxis</h1>

<%= render 'form' %>

<%= link_to 'Back', taxes_path %>

app/views/taxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tax rate:</b>
  <%= @taxis.tax_rate %>
</p>


<%= link_to 'Edit', edit_taxis_path(@taxis) %> |
<%= link_to 'Back', taxes_path %>